pipeline:
    name: Deploy nginx
    identifier: Deploy_nginx
    allowStageExecutions: false
    projectIdentifier: nischitbootcamp
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Deploy
              identifier: Deploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: nginx
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables:
                                  - name: mysecret
                                    type: Secret
                                    value: nischit_secret
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: account.bootcampdockerhub
                                          imagePath: library/nginx
                                          tag: <+input>
                                      type: DockerRegistry
                              manifests:
                                  - manifest:
                                        identifier: GitHub_Manifest
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.EliGit
                                                    gitFetchType: Branch
                                                    paths:
                                                        - values.yml
                                                    repoName: ngfundamentals
                                                    branch: main
                                  - manifest:
                                        identifier: Templates_Manifest
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.EliGit
                                                    gitFetchType: Branch
                                                    paths:
                                                        - templates/app-deployment.yml
                                                        - templates/namespace.yml
                                                    repoName: ngfundamentals
                                                    branch: main
                                            skipResourceVersioning: false
                  infrastructure:
                      environmentRef: dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.bootcampgkecluster
                              namespace: internalbootcamp-nischit
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: K8sCanaryDeploy
                                name: Canary
                                identifier: Canary
                                spec:
                                    skipDryRun: false
                                    instanceSelection:
                                        type: Count
                                        spec:
                                            count: 1
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: Testing variable
                                identifier: Testing_variable
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo my secret pw is <+serviceConfig.serviceDefinition.spec.variables.mysecret>
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
